#!/usr/bin/env pwsh
function Invoke-EnvironmentVariables {
    $pwshConfigDir = $IsWindows `
        ? (Join-Path $env:LOCALAPPDATA pwsh)
        : (Join-Path $HOME .config pwsh)

    $envOverrideFile = $IsWindows `
        ? (Join-Path $pwshConfigDir pwshenv.ps1)
        : (Join-Path $pwshConfigDir pwshenv)

    if (Test-Path $envOverrideFile) {
        . $envOverrideFile
    }

    $env:PWSH_HOME = $env:PWSH_HOME ?? (Join-Path $HOME pwsh)
    $env:PWSH_CONFIG = $env:PWSH_CONFIG ?? (Join-Path $pwshConfigDir pwsh.json)
    $env:EDITOR = 'nvim'
}

# Load environment variables
Invoke-EnvironmentVariables

# Load modules
Get-ChildItem (Join-Path $env:PWSH_HOME modules\**\*.psm1) -File | ForEach-Object { Import-Module $_.FullName }

# Load init scripts
Get-ChildItem (Join-Path $env:PWSH_HOME init\*.ps1) -File | ForEach-Object { . $_.FullName }

