# Local Aliases
Set-Alias g-cap Invoke-GitCommitAndPush;
Set-Alias g-ca Invoke-GitCommitAll;
Set-Alias g-dt Invoke-GitDeployTest;
Set-Alias g-dp Invoke-GitDeployProd;
Set-Alias g-undo Invoke-GitUndoCommit;
Set-Alias g-curb Invoke-GitCurrentBranch;
Set-Alias g-discard Invoke-GitCheckout;
Set-Alias g-pf Invoke-GitPushForce;
Set-Alias g-p Invoke-GitPush;
Set-Alias g-c Invoke-GitCommit;
Set-Alias g-pb Invoke-GitPushBranch;
Set-Alias g-m Invoke-GitMerge;
Set-Alias g-rb Invoke-GitRebase;
Set-Alias g-st Invoke-GitWorkingStatus;
Set-Alias g-af Invoke-GitAffectedFiles;
Set-Alias g-cb Invoke-GitCreateBranch;
Set-Alias g-aa Invoke-GitAddAll;
Set-Alias g-sh Invoke-GitStash;
Set-Alias g-pl Invoke-GitPull;
Set-Alias g-b Invoke-GitCheckout;
Set-Alias g-db Invoke-GitDeleteBranch
Set-Alias g-clean Invoke-GitCleanLocalBranches

# Faster Aliases (possible conficts)
Set-Alias cap Invoke-GitCommitAndPush;
Set-Alias ca Invoke-GitCommitAll;
Set-Alias dt Invoke-GitDeployTest;
Set-Alias dp Invoke-GitDeployProd;
Set-Alias undo Invoke-GitUndoCommit;
Set-Alias curb Invoke-GitCurrentBranch;
Set-Alias discard Invoke-GitCheckout;
Set-Alias pf Invoke-GitPushForce;
Set-Alias p Invoke-GitPush;
Set-Alias c Invoke-GitCommit;
Set-Alias pb Invoke-GitPushBranch;
Set-Alias m Invoke-GitMerge;
Set-Alias rb Invoke-GitRebase;
Set-Alias st Invoke-GitWorkingStatus;
Set-Alias af Invoke-GitAffectedFiles;
Set-Alias cb Invoke-GitCreateBranch;
Set-Alias aa Invoke-GitAddAll;
Set-Alias sh Invoke-GitStash;
Set-Alias pl Invoke-GitPull;
Set-Alias b Invoke-GitCheckout;
Set-Alias db Invoke-GitDeleteBranch
Set-Alias cl Invoke-GitCleanLocalBranches

# External Aliases
Set-Alias gut git;
Set-Alias g gitui;
